from __future__ import annotations

import unittest
from datetime import timedelta
from typing import cast

from tmf_research.models.provenance import (
    FoldIdentity,
    InnerTrainDataset,
    InnerValidationDataset,
    InnerValidationPrediction,
    InnerValidationPredictions,
    InnerValidationRange,
    InnerValidationRow,
    OuterTestRange,
    SplitRole,
)
from tmf_research.models.training import train_phase4_model

from tests.unit.test_phase4_training import END, fold_manifest, inner_train_dataset, training_spec


class Phase4CapabilityTests(unittest.TestCase):
    def test_inner_train_rejects_outer_test_or_validation_roles(self) -> None:
        with self.assertRaisesRegex(ValueError, "split role"):
            FoldIdentity("outer-1", "inner-1", "OUTER_TEST")  # type: ignore[arg-type]
        with self.assertRaisesRegex(ValueError, "fold-manifest authority"):
            FoldIdentity("outer-1", "inner-1", SplitRole.INNER_VALIDATION)
        manifest = fold_manifest()
        self.assertEqual(manifest.fold(SplitRole.INNER_TRAIN).role, SplitRole.INNER_TRAIN)
        self.assertEqual(manifest.fold(SplitRole.OUTER_TEST).role, SplitRole.OUTER_TEST)

    def test_probabilities_cannot_be_fabricated_outside_model_composition(self) -> None:
        training = train_phase4_model(inner_train_dataset(), training_spec())
        validation_range = InnerValidationRange.for_parent(
            training.preprocessor.provenance,
        )
        validation = InnerValidationDataset.create(
            validation_range,
            rows=(
                InnerValidationRow(
                    END + timedelta(minutes=2),
                    {"return_1m": 1.0, "basis": 20.0},
                    "LONG",
                    1.0,
                ),
            ),
        )

        with self.assertRaisesRegex(ValueError, "generated by Phase 4"):
            InnerValidationPrediction(
                END + timedelta(minutes=2),
                0.99,
                1,
                0.99,
                1,
                1.0,
                object(),
            )
        generated = training.predict_inner_validation(validation)
        self.assertEqual(generated.model_hash, training.model.content_hash)
        with self.assertRaisesRegex(ValueError, "generated by Phase 4"):
            InnerValidationPredictions(
                validation.provenance,
                training.preprocessor.content_hash,
                "0" * 64,
                generated.rows,
                object(),
            )

    def test_validation_capability_is_bound_to_exact_parent_training_manifest(self) -> None:
        training = train_phase4_model(inner_train_dataset(), training_spec())
        other_train = InnerTrainDataset.create(
            manifest=fold_manifest("e" * 64),
            rows=inner_train_dataset().rows,
        )
        other_training = train_phase4_model(other_train, training_spec())
        other_validation = InnerValidationDataset.create(
            InnerValidationRange.for_parent(other_training.preprocessor.provenance),
            rows=(
                InnerValidationRow(
                    END + timedelta(minutes=2),
                    {"return_1m": 1.0, "basis": 20.0},
                    "LONG",
                    1.0,
                ),
            ),
        )

        with self.assertRaisesRegex(ValueError, "parent training provenance"):
            training.predict_inner_validation(other_validation)

    def test_outer_test_rows_cannot_enter_inner_validation_range(self) -> None:
        training = train_phase4_model(inner_train_dataset(), training_spec())
        validation_range = InnerValidationRange.for_parent(
            training.preprocessor.provenance,
        )
        with self.assertRaisesRegex(ValueError, "validation interval"):
            InnerValidationDataset.create(
                validation_range,
                rows=(
                    InnerValidationRow(
                        END + timedelta(hours=2, minutes=1),
                        {"return_1m": 1.0, "basis": 20.0},
                        "LONG",
                        1.0,
                    ),
                ),
            )

        outer_test = OuterTestRange(training.preprocessor.provenance.manifest)
        with self.assertRaisesRegex(ValueError, "outer-test capability"):
            InnerValidationDataset.create(
                cast(InnerValidationRange, outer_test),
                rows=(
                    InnerValidationRow(
                        outer_test.start + timedelta(minutes=1),
                        {"return_1m": 1.0, "basis": 20.0},
                        "LONG",
                        1.0,
                    ),
                ),
            )


if __name__ == "__main__":
    unittest.main()
